#!/usr/bin/env python3
"""Draws the pixel-cat and pixel-dog skin sources (text grids for backend/pkg/skinpack) and preview sheets.

skins/pixel-cat and skins/pixel-dog are generated by this script and rewritten on every run: change the drawing
here, not the grids. Afterwards rebuild PetCore's pixel-cat.zip (see skins/README.md).

Body parts are filled pixel shapes; drawing a part outlines it (every 4-neighbour pixel outside the part turns
dark), back to front, so front parts get crisp edges over what's behind them. Faces and minis are hand-written.

usage: python3 skins/draw_skins.py skins <preview dir>
"""
import json
import os
import shutil
import struct
import sys
import zlib

ACTIONS = ["idle", "wave", "nudge", "sleep", "celebrate", "dance", "laugh", "cry", "yawn", "stretch",
           "think", "peek", "hide", "shrug", "facepalm", "cheer", "jump", "spin", "sit", "love"]
MOODS = ["content", "curious", "concerned", "excited", "sleepy", "bored",
         "playful", "proud", "shy", "grumpy", "calm", "lonely"]
N4 = ((1, 0), (-1, 0), (0, 1), (0, -1))

PALETTES = {
    "cat": {"k": "#2b1d14", "o": "#f4a340", "d": "#d9822b", "w": "#fff4e0", "p": "#f28fa0",
            "b": "#6ec6ff", "y": "#ffd84d", "r": "#e5484d"},
    "dog": {"k": "#2b1d14", "o": "#d9a066", "d": "#8f5a33", "w": "#fff4e0", "p": "#f28fa0",
            "b": "#6ec6ff", "y": "#ffd84d", "r": "#e5484d"},
}

# 12×5 faces placed at '@' (eyes on rows 1-2, nose row 3, mouth row 4); '.' shows the fur underneath.
FACES = {
    "content":   ["............", "..wk....wk..", "..kk....kk..", ".....pp.....", "....k..k...."],
    "curious":   ["........kk..", "..wk....wk..", "..kk....kk..", ".....pp.....", ".....kk....."],
    "concerned": ["...k....k...", "..wk....wk..", "..kk....kk..", ".....pp.....", "....kkkk...."],
    "excited":   ["............", ".wkk...wkk..", ".kkk...kkk..", ".....pp.....", "....kppk...."],
    "sleepy":    ["............", "............", ".kkk....kkk.", ".....pp.....", ".....k......"],
    "bored":     ["............", ".kkk....kkk.", "..kk....kk..", ".....pp.....", "....kkkk...."],
    "playful":   ["............", "..wk........", "..kk...kkk..", ".....pp.....", ".....pp....."],
    "proud":     ["............", "..kk....kk..", ".k..k..k..k.", ".....pp.....", "....k..k...."],
    "shy":       ["............", "............", "..kk....kk..", "pp...pp...pp", ".....kk....."],
    "grumpy":    [".kk......kk.", "...k....k...", "..kk....kk..", ".....pp.....", "....kkkk...."],
    "calm":      ["............", "............", "..kk....kk..", ".....pp.....", "....k..k...."],
    "lonely":    ["...k....k...", "..wk....wk..", "..kk....kk..", "..b..pp..b..", "....kkkk...."],
}

# 8×4 faces for the 16×16 minis (brow, eyes, nose, mouth).
MINI_FACES = {
    "content":   ["........", ".k....k.", "...pp...", "..k..k.."],
    "curious":   ["......k.", ".k....k.", "...pp...", "...kk..."],
    "concerned": ["..k..k..", ".k....k.", "...pp...", "..kkkk.."],
    "excited":   ["........", "kk....kk", "...pp...", "..kppk.."],
    "sleepy":    ["........", "........", "kk.pp.kk", "...k...."],
    "bored":     ["........", "kk....kk", "...pp...", "..kkkk.."],
    "playful":   ["........", ".k...kk.", "...pp...", "...pp..."],
    "proud":     [".k....k.", "k.k..k.k", "...pp...", "..k..k.."],
    "shy":       ["........", ".k....k.", "p..pp..p", "...kk..."],
    "grumpy":    ["kk....kk", ".k....k.", "...pp...", "..kkkk.."],
    "calm":      ["........", "kk....kk", "...pp...", "..k..k.."],
    "lonely":    ["..k..k..", ".k....k.", "b..pp..b", "..kkkk.."],
}


class Canvas:
    def __init__(self, size=32):
        self.size = size
        self.px = [["."] * size for _ in range(size)]
        self.face = None  # (x, y) of '@'

    def set(self, x, y, c):
        if 0 <= x < self.size and 0 <= y < self.size:
            self.px[y][x] = c

    def draw(self, part, dx=0, dy=0):
        """Paints a part and outlines it."""
        pts = {(x + dx, y + dy): c for (x, y), c in part.items()}
        for (x, y), c in pts.items():
            self.set(x, y, c)
        for (x, y) in pts:
            for ox, oy in N4:
                if (x + ox, y + oy) not in pts:
                    self.set(x + ox, y + oy, "k")

    def put(self, part, dx=0, dy=0):
        """Paints without an outline (details, props)."""
        for (x, y), c in part.items():
            self.set(x + dx, y + dy, c)

    def grid(self):
        rows = [row[:] for row in self.px]
        if self.face:
            fx, fy = self.face
            rows[fy][fx] = "@"
        return "".join("".join(r) + "\n" for r in rows)

    def resolved(self, mood=None):
        """The grid as the apps see a still: '@' painted as fur and the mood face drawn over it."""
        rows = [row[:] for row in self.px]
        if self.face and mood:
            fx, fy = self.face
            rows[fy][fx] = "o"
            for y, line in enumerate(FACES[mood]):
                for x, c in enumerate(line):
                    if c != ".":
                        rows[fy + y][fx + x] = c
        return rows


def rows(part, y0, halves, c, center=16):
    for i, n in enumerate(halves):
        for x in range(center - n, center + n):
            part[(x, y0 + i)] = c


def rect(part, x0, y0, x1, y1, c):
    for y in range(y0, y1 + 1):
        for x in range(x0, x1 + 1):
            part[(x, y)] = c


def mirrored(part, size=32):
    return {(size - 1 - x, y): c for (x, y), c in part.items()}


def pixels(spec, c):
    return {(x, y): c for x, y in spec}


# ---------- parts (canonical sitting pose, head centre x 15.5) ----------

def head_part(sp):
    p = {}
    rows(p, 7, [6, 8, 9, 10, 10, 10, 10, 10, 10, 10, 9, 8, 7, 5], "o")
    if sp == "cat":
        ear = {(8, 3): "o", (8, 4): "o", (9, 4): "o", (8, 5): "o", (9, 5): "p", (10, 5): "o",
               (8, 6): "o", (9, 6): "p", (10, 6): "p", (11, 6): "o"}
        p.update(ear)
        p.update(mirrored(ear))
        for y in (8, 9, 10):
            p[(15, y)] = p[(16, y)] = "d"
        for y in (9, 10):
            p[(12, y)] = p[(19, y)] = "d"
    else:
        rect(p, 11, 11, 14, 14, "d")  # eye patch; the face draws the eye over it
    rect(p, 13, 15, 18, 15, "w")
    rect(p, 12, 16, 19, 17, "w")
    rect(p, 13, 18, 18, 18, "w")
    return p


def dog_ears():
    ear = {}
    for x0, x1, y in ((6, 8, 8), (5, 8, 9), (4, 7, 10), (4, 7, 11), (4, 7, 12), (4, 7, 13), (4, 6, 14), (5, 6, 15)):
        rect(ear, x0, y, x1, y, "d")
    return ear


def body_part(paws=True, halves=(6, 7, 8, 8, 8, 8, 8, 8, 7), y0=20):
    p = {}
    rows(p, y0, halves, "o")
    last = y0 + len(halves) - 1
    rect(p, 14, y0 + 2, 17, y0 + 2, "w")
    rect(p, 13, y0 + 3, 18, last - 1, "w")
    rect(p, 14, last, 17, last, "w")
    if paws:
        rect(p, 10, last - 1, 12, last, "w")
        rect(p, 19, last - 1, 21, last, "w")
    return p


def tail_part(sp):
    if sp == "cat":
        spine = [(23, 27), (24, 27), (25, 26), (26, 25), (26, 24), (27, 23), (27, 22), (27, 21), (26, 20)]
    else:
        spine = [(23, 26), (24, 25), (25, 24), (26, 23), (27, 22)]
    p = {}
    for i, (x, y) in enumerate(spine):
        c = "d" if i >= len(spine) - 2 else "o"
        p[(x, y)] = p[(x + 1, y)] = c
    return p


def arm_up(side, lift=0, reach=0):
    """A raised arm beside the head: shoulder into the body, forearm up, paw on top."""
    p = {}
    rect(p, 3, 19, 8, 22, "o")  # shoulder up to the cheek, so no gap shows between arm and head
    rect(p, 3, 14 - lift, 4, 22, "o")
    rect(p, 2 - reach, 12 - lift, 4 - reach, 13 - lift, "w")
    return p if side == "left" else mirrored(p)


def arm_out(side, y=21):
    """An arm held out sideways, palm up (shrug)."""
    p = {}
    rect(p, 3, y, 9, y + 1, "o")
    rect(p, 2, y - 2, 3, y - 1, "w")
    return p if side == "left" else mirrored(p)


def paw_over(x0, y0, x1, y1, arm_x):
    p = {}
    rect(p, arm_x, y1 + 1, arm_x + 1, 21, "o")
    rect(p, x0, y0, x1, y1, "w")
    return p


# ---------- props ----------

def sparkle(x, y):
    return pixels([(x, y - 1), (x - 1, y), (x, y), (x + 1, y), (x, y + 1)], "y")


def heart(x, y):
    shape = [".r.r.", "rrrrr", ".rrr.", "..r.."]
    return {(x + i, y + j): "r" for j, line in enumerate(shape) for i, c in enumerate(line) if c == "r"}


def zee(x, y):
    shape = ["bbb", ".b.", "bbb"]
    return {(x + i, y + j): "b" for j, line in enumerate(shape) for i, c in enumerate(line) if c == "b"}


def note(x, y):
    shape = [".kk", ".k.", "kk."]
    return {(x + i, y + j): "k" for j, line in enumerate(shape) for i, c in enumerate(line) if c == "k"}


def closed_eyes(c, dx=0, dy=0):
    c.put(pixels([(12, 13), (13, 13), (18, 13), (19, 13)], "k"), dx, dy)


# ---------- poses ----------

def sitting(sp, dx=0, dy=0, head_dy=0, face=True, paws=True, tail=True, body=None):
    c = Canvas()
    if tail:
        c.draw(tail_part(sp), dx, dy)
    c.draw(body if body is not None else body_part(paws), dx, dy)
    c.draw(head_part(sp), dx, dy + head_dy)
    if sp == "dog":
        ears = dog_ears()
        c.draw(ears, dx, dy + head_dy)
        c.draw(mirrored(ears), dx, dy + head_dy)
    if face:
        c.face = (10 + dx, 11 + dy + head_dy)
    return c


def actions(sp):
    """action → (frame names in play order, still index, {frame name: canvas})."""
    out = {}

    def add(action, frames, order, still):
        out[action] = ([f"{action}/{i}" for i in order], still, {f"{action}/{i}": c for i, c in enumerate(frames)})

    blink = sitting(sp, face=False)
    closed_eyes(blink)
    add("idle", [sitting(sp), sitting(sp, head_dy=1), blink], [0, 0, 0, 1, 1, 0, 0, 2], 0)

    waves = []
    for reach, lift in ((0, 0), (1, 1)):
        c = sitting(sp)
        c.draw(arm_up("right", lift=lift, reach=-reach))
        waves.append(c)
    add("wave", waves, [0, 1, 0, 1], 1)

    add("nudge", [sitting(sp, dx=-2), sitting(sp, dx=2)], [0, 1, 0, 1], 0)

    sleeps = []
    for i in range(2):
        c = sitting(sp, head_dy=3, face=False, tail=False,
                    body=body_part(paws=False, halves=(8, 10, 11, 11, 11, 11, 11, 11, 10)))
        closed_eyes(c, dy=3)
        wrap = {}
        rect(wrap, 7, 27, 20, 28, "o")
        rect(wrap, 7, 27, 8, 28, "d")
        c.draw(wrap)
        c.put(zee(24, 5 - i * 2))
        if i:
            c.put(zee(28, 1))
        sleeps.append(c)
    add("sleep", sleeps, [0, 0, 1, 1], 0)

    celebrates = []
    for i, dy in enumerate((0, -2)):
        c = sitting(sp, dy=dy)
        c.draw(arm_up("left", lift=-dy), 0, dy)
        c.draw(arm_up("right", lift=-dy), 0, dy)
        for x, y in (((1, 3), (29, 5), (26, 1)), ((2, 6), (28, 2), (5, 1)))[i]:
            c.put(sparkle(x, y))
        celebrates.append(c)
    add("celebrate", celebrates, [0, 1, 0, 1], 1)

    dances = []
    for side, dx, nx in (("left", -1, 26), ("right", 1, 3)):
        c = sitting(sp, dx=dx)
        c.draw(arm_up(side), dx, 0)
        c.put(note(nx, 3))
        dances.append(c)
    add("dance", dances, [0, 1, 0, 1], 0)

    add("laugh", [sitting(sp), sitting(sp, dy=1)], [0, 1, 0, 1], 0)

    cries = []
    for drop in (0, 2):
        c = sitting(sp)
        c.put(pixels([(12, 16 + drop), (12, 17 + drop), (19, 16 + drop), (19, 17 + drop)], "b"))
        cries.append(c)
    add("cry", cries, [0, 1], 1)

    yawning = sitting(sp, head_dy=-1, face=False)
    closed_eyes(yawning, dy=-1)
    mouth = {}
    rect(mouth, 14, 15, 17, 16, "p")
    yawning.draw(mouth, 0, -1)
    add("yawn", [sitting(sp), yawning], [0, 1, 1, 1, 0], 1)

    stretches = []
    for head_dy in (5, 6):
        c = sitting(sp, head_dy=head_dy, paws=False)
        reach = {}
        rect(reach, 2, 27, 9, 28, "o")
        rect(reach, 2, 27, 3, 28, "w")
        c.draw(reach)
        c.draw(mirrored(reach))
        stretches.append(c)
    add("stretch", stretches, [0, 1], 0)

    thinks = []
    for i in range(2):
        c = sitting(sp)
        c.draw(paw_over(18, 18, 21, 19, 19))
        dots = {}
        rect(dots, 25, 8, 26, 9, "w")
        if i:
            rect(dots, 27, 3, 29, 5, "w")
        c.draw(dots)
        thinks.append(c)
    add("think", thinks, [0, 1], 0)

    peeks = []
    for dy in (13, 11):
        c = Canvas()
        c.draw(head_part(sp), 0, dy)
        if sp == "dog":
            c.draw(dog_ears(), 0, dy)
            c.draw(mirrored(dog_ears()), 0, dy)
        c.face = (10, 11 + dy)
        peeks.append(c)
    add("peek", peeks, [0, 1], 1)

    hides = []
    for peek in (False, True):
        c = sitting(sp, face=False)
        if peek:
            c.put(pixels([(12, 12), (13, 12), (12, 13), (13, 13)], "k"))
            c.draw(paw_over(17, 11, 21, 14, 19))
        else:
            c.draw(paw_over(10, 11, 14, 14, 11))
            c.draw(paw_over(17, 11, 21, 14, 19))
        c.put(pixels([(15, 16), (16, 16)], "k"))
        hides.append(c)
    add("hide", hides, [0, 0, 1, 0], 0)

    shrugs = []
    for y, head_dy in ((21, 1), (19, 0)):
        c = sitting(sp, head_dy=head_dy)
        c.draw(arm_out("left", y))
        c.draw(arm_out("right", y))
        shrugs.append(c)
    add("shrug", shrugs, [0, 1], 1)

    palms = []
    for head_dy in (0, 1):
        c = sitting(sp, head_dy=head_dy, face=False)
        c.put(pixels([(12, 13 + head_dy), (13, 13 + head_dy)], "k"))
        c.put(pixels([(x, 16 + head_dy) for x in range(14, 18)], "k"))
        c.draw(paw_over(16, 10 + head_dy, 22, 14 + head_dy, 19))
        palms.append(c)
    add("facepalm", palms, [0, 1], 0)

    cheers = []
    for side, sx in (("right", 28), ("left", 3)):
        c = sitting(sp)
        c.draw(arm_up(side, lift=1))
        c.draw(sparkle(sx, 3))
        cheers.append(c)
    add("cheer", cheers, [0, 1], 0)

    crouch = sitting(sp, head_dy=2, body=body_part(halves=(7, 8, 8, 8, 8, 8, 7), y0=22))
    add("jump", [crouch, sitting(sp, dy=-2), sitting(sp, dy=-3)], [0, 1, 2, 1, 0], 2)

    back = sitting(sp, face=False)
    fur = {}
    rows(fur, 7, [6, 8, 9, 10, 10, 10, 10, 10, 10, 10, 9, 8, 7, 5], "o")
    back.put({k: v for k, v in fur.items() if head_part(sp).get(k) in ("w", "d")})
    for y in (9, 11, 13):
        back.put(pixels([(x, y) for x in range(13, 19)], "d"))
    back.put(pixels([(1, 14), (1, 15), (30, 18), (30, 19)], "y"))
    front = sitting(sp)
    front.put(pixels([(30, 14), (30, 15), (1, 18), (1, 19)], "y"))
    add("spin", [front, back], [0, 1, 0, 1], 0)

    loaf = sitting(sp, paws=False, tail=False)
    wrap = {}
    rect(wrap, 10, 27, 23, 28, "o")
    rect(wrap, 22, 27, 23, 28, "d")
    loaf.draw(wrap)
    add("sit", [loaf], [0], 0)

    loves = []
    for i in range(2):
        c = sitting(sp)
        c.draw(heart(24, 5 - i * 3))
        if i:
            c.draw(heart(3, 6))
        loves.append(c)
    add("love", loves, [0, 1], 1)

    return out


def mini(sp, mood):
    c = Canvas(16)
    head = {}
    rows(head, 3, [5, 6, 7, 7, 7, 7, 7, 7, 7, 6, 5, 3], "o", center=8)
    if sp == "cat":
        ear = {(2, 0): "o", (2, 1): "o", (3, 1): "o", (2, 2): "o", (3, 2): "p", (4, 2): "o"}
        head.update(ear)
        head.update(mirrored(ear, 16))
        head[(7, 4)] = head[(8, 4)] = "d"
    rect(head, 5, 9, 10, 11, "w")
    c.draw(head)
    if sp == "dog":
        ear = {}
        rect(ear, 0, 4, 2, 9, "d")
        c.draw(ear)
        c.draw(mirrored(ear, 16))
    for y, line in enumerate(MINI_FACES[mood]):
        for x, ch in enumerate(line):
            if ch != ".":
                c.set(4 + x, 6 + y, ch)
    return c


def write_skin(root, sp, skin_id, name):
    folder = os.path.join(root, skin_id)
    shutil.rmtree(folder, ignore_errors=True)
    acts = actions(sp)
    meta_actions = {}
    for action in ACTIONS:
        order, still, frames = acts[action]
        meta_actions[action] = {"frames": order, "still": still}
        for frame_name, canvas in frames.items():
            write(os.path.join(folder, "body", frame_name + ".txt"), canvas.grid())
    for mood in MOODS:
        write(os.path.join(folder, "face", mood + ".txt"), "".join(line + "\n" for line in FACES[mood]))
        write(os.path.join(folder, "mini", mood + ".txt"), mini(sp, mood).grid())
    meta = {"id": skin_id, "name": name, "fps": 8, "face_base": "o", "palette": PALETTES[sp], "actions": meta_actions}
    write(os.path.join(folder, "meta.json"), json.dumps(meta, indent=2) + "\n")
    return acts


def write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(text)


# ---------- preview sheets (pure-Python PNG) ----------

def hex_rgb(h):
    return tuple(int(h[i:i + 2], 16) for i in (1, 3, 5))


def sheet(path, cells, palette, cols, scale=4, gap=4):
    """cells: list of pixel-row grids (lists of strings/lists of chars)."""
    size = len(cells[0])
    cell = size * scale + gap
    count_rows = (len(cells) + cols - 1) // cols
    w, h = cols * cell + gap, count_rows * cell + gap
    img = [[(236, 236, 240) if ((x // 8) + (y // 8)) % 2 else (248, 248, 250) for x in range(w)] for y in range(h)]
    for i, grid in enumerate(cells):
        ox, oy = gap + (i % cols) * cell, gap + (i // cols) * cell
        for y, line in enumerate(grid):
            for x, ch in enumerate(line):
                if ch in ".":
                    continue
                rgb = hex_rgb(palette["o" if ch == "@" else ch])
                for sy in range(scale):
                    for sx in range(scale):
                        img[oy + y * scale + sy][ox + x * scale + sx] = rgb
    raw = b"".join(b"\x00" + bytes(v for px in row for v in px) for row in img)

    def chunk(tag, data):
        return struct.pack(">I", len(data)) + tag + data + struct.pack(">I", zlib.crc32(tag + data) & 0xFFFFFFFF)

    png = b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", struct.pack(">IIBBBBB", w, h, 8, 2, 0, 0, 0)) + \
        chunk(b"IDAT", zlib.compress(raw, 9)) + chunk(b"IEND", b"")
    with open(path, "wb") as f:
        f.write(png)


def main():
    root, preview = sys.argv[1], sys.argv[2]
    os.makedirs(preview, exist_ok=True)
    for sp, skin_id, name in (("cat", "pixel-cat", "Pixel Cat"), ("dog", "pixel-dog", "Pixel Dog")):
        acts = write_skin(root, sp, skin_id, name)
        palette = PALETTES[sp]
        # every distinct frame of every action with the content face, 8 per row
        cells = []
        for action in ACTIONS:
            order, _, frames = acts[action]
            distinct = list(dict.fromkeys(order))
            row = [frames[n].resolved("content") for n in distinct]
            row += [[["."] * 32 for _ in range(32)]] * (8 - len(row))
            cells += row
        sheet(os.path.join(preview, f"{skin_id}-actions.png"), cells, palette, cols=8)
        # the idle still with all 12 faces, then the 12 minis at double scale
        idle = acts["idle"][2]["idle/0"]
        sheet(os.path.join(preview, f"{skin_id}-faces.png"), [idle.resolved(m) for m in MOODS], palette, cols=6, scale=6)
        sheet(os.path.join(preview, f"{skin_id}-minis.png"), [mini(sp, m).resolved() for m in MOODS], palette, cols=6, scale=8)
    print("wrote skins and previews")


if __name__ == "__main__":
    main()
